### ISSUE TITLE
Codesign error

### ISSUE THREAD

**Issue by bmichotte** [webcracy/motion-sparkle#17]
Hi, 

I've got some issue with sparkle and your gem.

```bash
 Codesign ./build/MacOSX-10.8-Release/HSTracker.app
./build/MacOSX-10.8-Release/HSTracker.app: unsealed contents present in the root directory of an embedded framework
In subcomponent: /Users/benjamin/Documents/workspace/hstracker/build/MacOSX-10.8-Release/HSTracker.app/Contents/Frameworks/Sparkle.framework
rake aborted!
Command failed with status (1): [/usr/bin/codesign --deep --force --sign "D...]
/Library/RubyMotion/lib/motion/project/app.rb:86:in `codesign'
/Library/RubyMotion/lib/motion/project/template/osx.rb:53:in `block (2 levels) in <top (required)>'
Tasks: TOP => archive => build:release
(See full trace by running task with --trace)
```

Do you have idea why ?

I'm using 10.10.4, with all versions updated.

**Comment by webcracy** [comment]
Hi, are you using master/0.0.6 or version 0.0.5?

**Comment by bmichotte** [comment]
0.0.5

**Comment by bmichotte** [comment]
Ok, using master seems to fix the issue

**Comment by webcracy** [comment]
Great. I have yet to release it.

**Comment by bmichotte** [comment]
The strange part of it, is that the problem didn't appear at the first time, it appears a day after the first release
